version: '3.8'
services:
  #docker compose --env-file=.env.docker up -d 

#Python Service
  python_server:
    build:
      context: .
      dockerfile: dockerfiles/python.Dockerfile
    container_name: python_server
    restart: unless-stopped
    tty: true
    ports: 
      - "${SERVER_PORT}:5000"
    environment: 
      SERVICE_NAME: python_flask
    working_dir: /usr/src/app
    volumes: 
      - ${SERVER_ROOT_FOLDER}:/usr/src/app
    networks: 
      - app-network

  #Nginx Service
  client:
    build:
      context: .
      dockerfile: dockerfiles/nginx.Dockerfile
    container_name: client
    restart: unless-stopped
    tty: true
    ports:
      - "${CLIENT_PORT_HTTP}:80"
      - "${CLIENT_PORT_HTTPS}:443"
    volumes:
      - ${CLIENT_ROOT_FOLDER}:/var/www
    networks:
      - app-network

  
#Docker Networks
networks:
  app-network:
    driver: bridge
